version: "3.8"

services:
  mysql:
    image: mysql
    container_name: mysql-db-paypay
    volumes:
      - /var/lib/docker/volumes
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${APP_DB_PASSWORD}
      - MYSQL_DATABASE=${APP_DB}
