const FETCH_ALL_USERS_SUCCESS = "@USER/FETCH_ALL_SUCCESS";

const FETCH_ALL_USERS = "@USER/FETCH_ALL";

const FETCH_ALL_USERS_ERROR = "@USER/FETCH_ALL_ERROR";

const FETCH_USER_SUCCESS = "@USER/FETCH_USER_SUCCESS";

const FETCH_USER = "@USER/FETCH_USER";

const FETCH_USER_ERROR = "@USER/FETCH_USER_ERROR";

export default {
  FETCH_ALL_USERS_SUCCESS,
  FETCH_ALL_USERS,
  FETCH_ALL_USERS_ERROR,
  FETCH_USER_SUCCESS,
  FETCH_USER,
  FETCH_USER_ERROR,
} as const;
