const FETCH_ALL_USERS_SUCCESS = "@USER/FETCH_ALL_SUCCESS";

const FETCH_ALL_USERS = "@USER/FETCH_ALL";

const FETCH_ALL_USERS_ERROR = "@USER/FETCH_ALL_ERROR";

export default {
  FETCH_ALL_USERS_SUCCESS,
  FETCH_ALL_USERS,
  FETCH_ALL_USERS_ERROR,
} as const;
