const FETCH_ALL_REVEIWS_SUCCESS = "@REVIEW/FETCH_ALL_SUCCESS";

const FETCH_ALL_REVEIWS = "@REVIEW/FETCH_ALL";

const FETCH_ALL_REVEIWS_ERROR = "@REVIEW/FETCH_ALL_ERROR";

export default {
  FETCH_ALL_REVEIWS_SUCCESS,
  FETCH_ALL_REVEIWS,
  FETCH_ALL_REVEIWS_ERROR,
} as const;
