const FETCH_ALL_REVIEWS_SUCCESS = "@USER/FETCH_ALL_SUCCESS";

const FETCH_ALL_REVIEWS = "@USER/FETCH_ALL";

const FETCH_ALL_REVIEWS_ERROR = "@REVIEW/FETCH_ALL_ERROR";

const FETCH_REVIEW_SUCCESS = "@REVIEW/FETCH_REVIEW_SUCCESS";

const FETCH_REVIEW = "@REVIEW/FETCH_REVIEW";

const FETCH_REVIEW_ERROR = "@REVIEW/FETCH_REVIEW_ERROR";

const ADD_REVIEW_SUCCESS = "@REVIEW/ADD_REVIEW_SUCCESS";

const ADD_REVIEW = "@REVIEW/ADD_REVIEW";

const ADD_REVIEW_ERROR = "@REVIEW/ADD_REVIEW_ERROR";

const UPDATE_REVIEW_SUCCESS = "@REVIEW/UPDATE_REVIEW_SUCCESS";

const UPDATE_REVIEW = "@REVIEW/UPDATE_REVIEW";

const UPDATE_REVIEW_ERROR = "@REVIEW/UPDATE_REVIEW_ERROR";

const DELETE_REVIEW_SUCCESS = "@REVIEW/DELETE_REVIEW_SUCCESS";

const DELETE_REVIEW = "@REVIEW/DELETE_REVIEW";

const DELETE_REVIEW_ERROR = "@REVIEW/DELETE_REVIEW_ERROR";

export default {
  FETCH_ALL_REVIEWS_SUCCESS,
  FETCH_ALL_REVIEWS,
  FETCH_ALL_REVIEWS_ERROR,
  FETCH_REVIEW_SUCCESS,
  FETCH_REVIEW,
  FETCH_REVIEW_ERROR,
  ADD_REVIEW_SUCCESS,
  ADD_REVIEW,
  ADD_REVIEW_ERROR,
  UPDATE_REVIEW_SUCCESS,
  UPDATE_REVIEW,
  UPDATE_REVIEW_ERROR,
  DELETE_REVIEW_SUCCESS,
  DELETE_REVIEW,
  DELETE_REVIEW_ERROR,
} as const;
